apiVersion: v1
kind: Service
metadata:
  name: {{ template "naipi-agent.fullname" . }}
  labels:
    app: {{ template "naipi-agent.name" . }}
    chart: {{ template "naipi-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 18861
      targetPort: rpyc
      protocol: TCP
      name: rpyc
  selector:
    app: {{ template "naipi-agent.name" . }}
    release: {{ .Release.Name }}